apiVersion: v1
kind: Service
metadata:
  name: write-v2-var~name~
  labels:
    version: v2
    service: atomi.core.db-var~name~
    env: dev
  annotations:
    created-by: var~name~
spec:
  selector:
    version: v2
    service: atomi.core.db-var~name~
    env: dev
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000 
    protocol: TCP