apiVersion: v1
kind: Pod
metadata:
  name: write-v2-var~name~
  labels:
    version: v2
    service: atomi.core.db-var~name~
    env: dev
  annotations:
    created-by: var~name~
spec:
  containers:
  - name: api
    image: "kirinnee/thp-node:write-v2"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ENV
      value: DEV
    - name: CONFIG_PATH
      value: config.yaml
    ports:
    - containerPort: 3000
      name:  http
    volumeMounts:
      - name: data
        mountPath: "/data"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: write-v2-pvc-var~name~
  restartPolicy: Always