apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: write-v2-pvc-var~name~
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi