apiVersion: v1
kind: Pod
metadata:
  name: write-v2-kirin
  labels:
    version: v2
    service: atomi.core.db-kirin
    env: dev
  annotations:
    created-by: kirin
spec:
  containers:
  - name: api
    image: "kirinnee/thp-node:write-v2"
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ENV
      value: DEV
    - name: CONFIG_PATH
      value: config.yaml
    ports:
    - containerPort: 3000
      name:  http
  restartPolicy: Always