apiVersion: v1
kind: Service
metadata:
  name: write-v2-kirin
  labels:
    version: v2
    service: atomi.core.db-kirin
    env: dev
  annotations:
    created-by: kirin
spec:
  selector:
    version: v2
    service: atomi.core.db-kirin
    env: dev
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000 
    protocol: TCP