apiVersion: v1
kind: Pod
metadata:
  name: random-v2-var~name~
  labels:
    version: v2
    service: atomi.core.random-var~name~
  annotations:
    created-by: var~name~
spec: 
  containers:
  - name: api
    image: "kirinnee/thp-node:random-v2"
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          name: random-v2-cm-var~name~
          key: environment
    - name: CONFIG_PATH
      valueFrom:
        configMapKeyRef:
          name: random-v2-cm-var~name~
          key: path_to_my_config
    ports:
    - containerPort: 3000
      name:  http
    volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: random-v2-cm-fs-var~name~
  restartPolicy: Always